version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    #ports:
    #  - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  api:
    build:
      context: .
    tty: true
    ports:
     
     - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
#    command: bash -c "python manage.py migrate
#    && python manage.py runserver 0.0.0.0:8000"
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
volumes:
  db:
    driver: local

