# Generated by Django 4.1.7 on 2023-03-01 14:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=240, unique=True)),
                ('password', models.CharField(max_length=240)),
                ('is_staff', models.BooleanField(default=False, verbose_name=('staff status',))),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=35, null=True, verbose_name='название курса')),
                ('preview', models.CharField(blank=True, max_length=50, null=True, verbose_name=' фото урока')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='описание курса')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=35, null=True, verbose_name='название урока')),
                ('preview', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=350, null=True, verbose_name='описание урока')),
                ('reference', models.CharField(blank=True, max_length=55, null=True, verbose_name='ссылка на видео')),
                ('smth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smthin', to='spa.course')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(False, False), (True, True)], default=True)),
                ('subscribed_on', models.DateTimeField(auto_now_add=True)),
                ('period', models.TimeField(auto_now=True, choices=[(86400, 'день=86400'), (604800, 'неделя=604800'), (2419200, 'месяц=2419200')], max_length=10, null=True)),
                ('course_subscribe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spa.course')),
                ('lesson_subscribe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spa.lesson')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Персональная ссылка')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Информация о себе')),
                ('avatar', models.ImageField(blank=True, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg'))], verbose_name='Аватар профиля')),
                ('date_birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('following', models.ManyToManyField(blank=True, null=True, related_name='followers', to='spa.usersubscription', verbose_name='Подписки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_payment', models.DateTimeField(blank=True, null=True, verbose_name='дата оплаты')),
                ('sum_of_payment', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='сумма оплаты')),
                ('form_of_payment', models.CharField(choices=[('card', 'перевод на счет'), ('cash', 'наличные')], default='card', max_length=10, verbose_name='способ оплаты наличные или перевод')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spa.course', verbose_name='курс')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spa.lesson', verbose_name='урок')),
                ('pro_filee', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='spa.profile', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'платеж',
                'verbose_name_plural': 'платежи',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='pro_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spa.profile'),
        ),
    ]
