# Generated by Django 4.1.7 on 2023-02-16 08:07

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='описание курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='название курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, max_length=350, null=True, verbose_name='описание урока'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='name',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='название урока'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='картинка к уроку'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='аватарка'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='город'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='телефон'),
        ),
    ]
