# Generated by Django 4.1.7 on 2023-02-19 18:19

from django.db import migrations, models
import django.db.models.deletion
import spa.models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0003_lesson_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'урок', 'verbose_name_plural': 'уроки'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', spa.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.ForeignKey(blank=True, max_length=350, null=True, on_delete=django.db.models.deletion.CASCADE, to='spa.course', verbose_name='описание урока'),
        ),
    ]
