# Generated by Django 4.1.7 on 2023-02-24 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0004_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='object_of_payment',
        ),
        migrations.AddField(
            model_name='payments',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spa.course', verbose_name='курс'),
        ),
        migrations.AddField(
            model_name='payments',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spa.lesson', verbose_name='урок'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name=('staff status',)),
        ),
        migrations.AlterField(
            model_name='payments',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='date_of_payment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата оплаты'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='form_of_payment',
            field=models.CharField(choices=[('card', 'перевод на счет'), ('cash', 'наличные')], default='card', max_length=10, verbose_name='способ оплаты наличные или перевод'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='sum_of_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='сумма оплаты'),
        ),
    ]
