# Generated by Django 4.1.7 on 2023-03-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0004_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name=('staff status',)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Персональная ссылка'),
        ),
    ]
