# Generated by Django 4.1.7 on 2023-02-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0004_alter_course_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, max_length=35, null=True, verbose_name='пользователь')),
                ('date_of_payment', models.DateTimeField(auto_now_add=True, verbose_name='дата оплаты')),
                ('object_of_payment', models.CharField(blank=True, max_length=45, null=True, verbose_name='оплаченый курс или урок')),
                ('sum_of_payment', models.IntegerField(blank=True, null=True, verbose_name='сумма оплаты')),
                ('form_of_payment', models.CharField(blank=True, max_length=45, null=True, verbose_name='способ оплаты наличные или перевод')),
            ],
            options={
                'verbose_name': 'платеж',
                'verbose_name_plural': 'платежи',
            },
        ),
        migrations.AlterField(
            model_name='lesson',
            name='reference',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='ссылка на видео'),
        ),
    ]
