# Generated by Django 4.1.7 on 2023-02-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0005_remove_payments_object_of_payment_payments_course_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name=('staff status',)),
        ),
    ]
