# Generated by Django 4.1.7 on 2023-02-21 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0006_remove_lesson_description_course_lessons_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.ForeignKey(blank=True, max_length=350, null=True, on_delete=django.db.models.deletion.CASCADE, to='spa.course', verbose_name='описание урока'),
        ),
    ]
