# Generated by Django 4.1.7 on 2023-03-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0006_paymentcheck_paymentchecklog_lesson_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name=('staff status',)),
        ),
    ]
