# Generated by Django 4.1.7 on 2023-02-21 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0007_lesson_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lessons_amount',
        ),
        migrations.AddField(
            model_name='course',
            name='lessons_amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spa.lesson'),
        ),
    ]
