# Generated by Django 4.1.7 on 2023-03-03 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0007_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Details',
            field=models.CharField(max_length=50, null=True, verbose_name='Детали'),
        ),
        migrations.AddField(
            model_name='payment',
            name='ErrorCode',
            field=models.CharField(max_length=50, null=True, verbose_name='Ошибка'),
        ),
        migrations.AddField(
            model_name='payment',
            name='Message',
            field=models.CharField(max_length=50, null=True, verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='payment',
            name='Success',
            field=models.CharField(max_length=50, null=True, verbose_name='Статус обработки'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name=('staff status',)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='spa.course', verbose_name='курс'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='spa.lesson', verbose_name='урок'),
        ),
    ]
