# Generated by Django 4.1.7 on 2023-02-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0008_remove_course_lessons_amount_course_lessons_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lessons_amount',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='название курса'),
        ),
    ]
