# Generated by Django 4.1.7 on 2023-03-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0008_payment_details_payment_errorcode_payment_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='Details',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='ErrorCode',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='Message',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='Success',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name=('staff status',)),
        ),
    ]
