# Generated by Django 4.1.7 on 2023-02-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0009_alter_course_lessons_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lessons_amount',
        ),
    ]
