# Generated by Django 4.1.7 on 2023-03-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0009_remove_payment_details_remove_payment_errorcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Details',
            field=models.CharField(max_length=50, null=True, verbose_name='Детали'),
        ),
        migrations.AddField(
            model_name='payment',
            name='ErrorCode',
            field=models.CharField(max_length=50, null=True, verbose_name='Ошибка'),
        ),
        migrations.AddField(
            model_name='payment',
            name='Message',
            field=models.CharField(max_length=50, null=True, verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='payment',
            name='Success',
            field=models.CharField(max_length=50, null=True, verbose_name='Статус обработки'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name=('staff status',)),
        ),
    ]
