# Generated by Django 4.1.7 on 2023-02-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0010_alter_course_preview_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' фото урока'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name=('staff status',)),
        ),
    ]
