# Generated by Django 4.1.7 on 2023-03-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0010_payment_details_payment_errorcode_payment_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Amount',
            field=models.CharField(max_length=50, null=True, verbose_name='Сумма'),
        ),
        migrations.AddField(
            model_name='payment',
            name='OrderId',
            field=models.CharField(max_length=50, null=True, verbose_name='Номер заказа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='PaymentId',
            field=models.CharField(max_length=50, null=True, verbose_name='Номер платежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='PaymentURL',
            field=models.CharField(max_length=50, null=True, verbose_name='Ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='payment',
            name='Status',
            field=models.CharField(max_length=50, null=True, verbose_name='Детали'),
        ),
        migrations.AddField(
            model_name='payment',
            name='TerminalKey',
            field=models.CharField(max_length=50, null=True, verbose_name='Детали'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name=('staff status',)),
        ),
    ]
