# Generated by Django 4.1.7 on 2023-02-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0011_alter_course_preview_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name=('staff status',)),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='preview',
            field=models.CharField(max_length=50),
        ),
    ]
