# Generated by Django 4.1.7 on 2023-03-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0015_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentCheck',
        ),
        migrations.DeleteModel(
            name='PaymentCheckLog',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name=('staff status',)),
        ),
    ]
