# Generated by Django 4.1.7 on 2023-03-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0016_delete_paymentcheck_delete_paymentchecklog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='status_send',
            field=models.BooleanField(choices=[(False, False), (True, True)], default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name=('staff status',)),
        ),
    ]
