# Generated by Django 4.1.7 on 2023-03-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0017_usersubscription_status_send_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(default=1, max_length=60, verbose_name='наименование'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name=('staff status',)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Персональная ссылка'),
        ),
    ]
