# Generated by Django 4.1.7 on 2023-03-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0019_usersubscription_user_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscription',
            old_name='user',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name=('staff status',)),
        ),
    ]
