# Generated by Django 4.1.7 on 2023-03-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0022_alter_customuser_is_staff_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name=('staff status',)),
        ),
    ]
