# Generated by Django 4.1.7 on 2023-03-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0023_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailinglog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing', models.CharField(max_length=100, verbose_name='Email')),
                ('result', models.CharField(max_length=100, verbose_name='Result')),
                ('last_attempt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name=('staff status',)),
        ),
    ]
