# Generated by Django 4.1.7 on 2023-03-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0024_mailinglog_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='following_subscription',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name=('staff status',)),
        ),
    ]
