# Generated by Django 4.1.7 on 2023-02-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0002_alter_user_managers_course_description_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='reference',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='ссылка на видео'),
        ),
    ]
