# Generated by Django 4.1.7 on 2023-02-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0005_payments_alter_lesson_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
        migrations.AddField(
            model_name='course',
            name='lessons_amount',
            field=models.ManyToManyField(blank=True, null=True, related_name='lessons', to='spa.lesson'),
        ),
    ]
