# Generated by Django 4.1.7 on 2023-02-21 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0010_remove_course_lessons_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='smth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smthin', to='spa.course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='описание урока'),
        ),
    ]
