# Generated by Django 4.1.7 on 2023-02-22 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0011_lesson_smth_alter_lesson_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
