# Generated by Django 4.1.7 on 2023-02-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0009_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name=('staff status',)),
        ),
    ]
