# Generated by Django 4.1.7 on 2023-03-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0021_alter_usersubscription_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'ordering': ('user',), 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name=('staff status',)),
        ),
    ]
